from tkinter import*
cr=Tk()
def name():
    ftname=Label(cr,text="Firstname")
    ftname.grid(row=0,column=0)
    lname=Label(cr,text="LastName")
    lname.grid(row=0,column=1)
    age=Label(cr,text="Age")
    age.grid(row=0,column=2)
    add=Label(cr,text="Address")
    add.grid(row=0,column=3)
    city=Label(cr,text="City")
    city.grid(row=0,column=4)
    zip=Label(cr,text="Zipcode")
    zip.grid(row=0,column=5)
    pas=Label(cr,text="Password")
    pas.grid(row=0,column=6)
    gender=Label(cr,text="Gender")
    gender.grid(row=0,column=7)

    fname=Entry(cr,width=30)
    fname.grid(row=1,column=0)
    lname=Entry(cr,width=30)
    lname.grid(row=1,column=1)
    age=Entry(cr,width=30)
    age.grid(row=1,column=2)
    add=Entry(cr,width=30)
    add.grid(row=1,column=3)
    city=Entry(cr,width=30)
    city.grid(row=1,column=4)
    zip=Entry(cr,width=30)
    zip.grid(row=1,column=5)
    pas=Entry(cr,width=30)
    pas.grid(row=1,column=6)
    gender=Entry(cr,width=30)
    gender.grid(row=1,column=7)
name()    
cr.mainloop()